# Generated by Django 3.2.16 on 2023-04-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('priority', models.IntegerField(default=9)),
                ('title', models.CharField(max_length=300)),
                ('estimated_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(choices=[(1, 'IN PROGRESS'), (2, 'TO DO'), (3, 'COMPLETED'), (4, 'BACKLOG'), (5, 'OUT OF SCOPE'), (6, 'CANCELLED')], default=2)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.IntegerField(choices=[(1, 'DUE TODAY'), (2, 'DUE TOMORROW'), (3, 'DUE THIS CYCLE'), (4, 'DUE NEXT CYCLE'), (5, 'UNPLANNED'), (6, 'COMPLETED')], default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('priority', models.IntegerField(default=9)),
                ('title', models.CharField(max_length=300)),
                ('estimated_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(choices=[(1, 'IN PROGRESS'), (2, 'TO DO'), (3, 'COMPLETED'), (4, 'BACKLOG'), (5, 'OUT OF SCOPE'), (6, 'CANCELLED')], default=2)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.IntegerField(choices=[(1, 'DUE TODAY'), (2, 'DUE TOMORROW'), (3, 'DUE THIS CYCLE'), (4, 'DUE NEXT CYCLE'), (5, 'UNPLANNED'), (6, 'COMPLETED')], default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('priority', models.IntegerField(default=9)),
                ('title', models.CharField(max_length=300)),
                ('estimated_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(choices=[(1, 'IN PROGRESS'), (2, 'TO DO'), (3, 'COMPLETED'), (4, 'BACKLOG'), (5, 'OUT OF SCOPE'), (6, 'CANCELLED')], default=2)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.IntegerField(choices=[(1, 'DUE TODAY'), (2, 'DUE TOMORROW'), (3, 'DUE THIS CYCLE'), (4, 'DUE NEXT CYCLE'), (5, 'UNPLANNED'), (6, 'COMPLETED')], default=5)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.milestone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='tasks.project'),
        ),
    ]
