# Generated by Django 3.2.16 on 2023-04-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('estimated_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='TO_DO', max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('estimated_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='TO_DO', max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('estimated_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='TO_DO', max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.milestone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='tasks.project'),
        ),
    ]
