# Generated by Django 3.2.16 on 2023-04-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='priority',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=9),
        ),
    ]
