# Generated by Django 3.2.16 on 2023-04-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230406_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.IntegerField(default=9),
        ),
    ]
