# Generated by Django 3.2.16 on 2023-04-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20230406_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('OUT_OF_SCOPE', 'Out Of Scope')], default='TO_DO', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('OUT_OF_SCOPE', 'Out Of Scope')], default='TO_DO', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('OUT_OF_SCOPE', 'Out Of Scope')], default='TO_DO', max_length=20),
        ),
    ]
