# Generated by Django 3.2.16 on 2023-04-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20230406_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
