# Generated by Django 3.2.16 on 2023-04-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20230406_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='due_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='due_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='due_today',
            field=models.BooleanField(default=False),
        ),
    ]
