# Generated by Django 3.2.16 on 2023-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20230417_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.IntegerField(choices=[(1, 'DUE TODAY'), (2, 'DUE TOMORROW'), (3, 'DUE THIS CYCLE'), (4, 'DUE NEXT CYCLE'), (5, 'UNPLANIFIED'), (6, 'COMPLETED')], default=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.IntegerField(choices=[(1, 'DUE TODAY'), (2, 'DUE TOMORROW'), (3, 'DUE THIS CYCLE'), (4, 'DUE NEXT CYCLE'), (5, 'UNPLANIFIED'), (6, 'COMPLETED')], default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.IntegerField(choices=[(1, 'DUE TODAY'), (2, 'DUE TOMORROW'), (3, 'DUE THIS CYCLE'), (4, 'DUE NEXT CYCLE'), (5, 'UNPLANIFIED'), (6, 'COMPLETED')], default=5),
        ),
    ]
