# Generated by Django 3.2.16 on 2023-04-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20230417_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.IntegerField(choices=[(1, 'DUE TODAY'), (2, 'DUE TOMORROW'), (3, 'DUE THIS CYCLE'), (4, 'DUE NEXT CYCLE'), (5, 'UNPLANNED'), (6, 'COMPLETED')], default=5),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('BACKLOG', 'Backlog'), ('OUT_OF_SCOPE', 'Out Of Scope')], default='TO_DO', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.IntegerField(choices=[(1, 'DUE TODAY'), (2, 'DUE TOMORROW'), (3, 'DUE THIS CYCLE'), (4, 'DUE NEXT CYCLE'), (5, 'UNPLANNED'), (6, 'COMPLETED')], default=5),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('BACKLOG', 'Backlog'), ('OUT_OF_SCOPE', 'Out Of Scope')], default='TO_DO', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.IntegerField(choices=[(1, 'DUE TODAY'), (2, 'DUE TOMORROW'), (3, 'DUE THIS CYCLE'), (4, 'DUE NEXT CYCLE'), (5, 'UNPLANNED'), (6, 'COMPLETED')], default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To do'), ('IN_PROGRESS', 'In progress'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('BACKLOG', 'Backlog'), ('OUT_OF_SCOPE', 'Out Of Scope')], default='TO_DO', max_length=20),
        ),
    ]
