# Generated by Django 3.2.16 on 2023-04-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20230418_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('TO_DO', 'To do'), ('COMPLETED', 'Completed'), ('BACKLOG', 'Backlog'), ('OUT_OF_SCOPE', 'Out Of Scope'), ('CANCELLED', 'Cancelled')], default='TO_DO', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('TO_DO', 'To do'), ('COMPLETED', 'Completed'), ('BACKLOG', 'Backlog'), ('OUT_OF_SCOPE', 'Out Of Scope'), ('CANCELLED', 'Cancelled')], default='TO_DO', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('TO_DO', 'To do'), ('COMPLETED', 'Completed'), ('BACKLOG', 'Backlog'), ('OUT_OF_SCOPE', 'Out Of Scope'), ('CANCELLED', 'Cancelled')], default='TO_DO', max_length=20),
        ),
    ]
