# Generated by Django 3.2.16 on 2023-04-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20230418_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.IntegerField(choices=[(1, 'IN PROGRESS'), (2, 'TO DO'), (3, 'COMPLETED'), (4, 'BACKLOG'), (5, 'OUT OF SCOPE'), (6, 'CANCELLED')], default=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'IN PROGRESS'), (2, 'TO DO'), (3, 'COMPLETED'), (4, 'BACKLOG'), (5, 'OUT OF SCOPE'), (6, 'CANCELLED')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'IN PROGRESS'), (2, 'TO DO'), (3, 'COMPLETED'), (4, 'BACKLOG'), (5, 'OUT OF SCOPE'), (6, 'CANCELLED')], default=2),
        ),
    ]
