# Generated by Django 3.2.16 on 2023-04-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
