# Generated by Django 3.2.16 on 2023-04-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='is_regular',
            field=models.BooleanField(default=False),
        ),
    ]
