# Generated by Django 3.2.16 on 2023-04-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_cycle_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
