# Generated by Django 3.2.16 on 2023-04-06 14:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_cycle_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('cycle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal.cycle')),
                ('title', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
            ],
            bases=('personal.cycle',),
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='cycle',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=4, seconds=14439)),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.challenge')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.eventtype')),
            ],
        ),
    ]
