# Generated by Django 3.2.16 on 2023-04-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='cycle_ptr',
        ),
        migrations.RemoveField(
            model_name='date',
            name='type',
        ),
        migrations.DeleteModel(
            name='DayRegister',
        ),
        migrations.RemoveField(
            model_name='event',
            name='challenge',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='DateType',
        ),
    ]
