# Generated by Django 3.2.16 on 2023-04-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20230422_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='is_regular',
            field=models.BooleanField(default=True),
        ),
    ]
