# Generated by Django 3.2.16 on 2023-04-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20230406_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extra_info_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='extra_info_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
