# Generated by Django 3.2.16 on 2023-04-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_worksession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
