# Generated by Django 3.2.16 on 2023-04-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_alter_worksession_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
