# Generated by Django 3.2.16 on 2023-04-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_dayregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayregister',
            old_name='type',
            new_name='comment',
        ),
    ]
