# Generated by Django 3.2.16 on 2023-04-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_rename_type_dayregister_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='duration',
        ),
    ]
